### ISSUE TITLE
Move repository to rdmorganiser/rdmo-plugins-... under what name? 

### ISSUE THREAD

**Issue by MyPyDavid** [MarcoReidelbach/MaRDMO-Plugin#51]
Do you want to have this repository moved to https://github.com/rdmorganiser?q=rdmo-plugins-&type=all&language=&sort= ?

I can create one under rdmorganiser but what should be the name? 
* `rdmo-plugins-mardmo`
* `rdmo-plugins-mardmo-export`
* ...?

I would then also like to refactor the code to make the Python/Django app name from `MaRDMO` into `rdmo_plugins_mardmo`

**Comment by MarcoReidelbach** [comment]
Feel free to do so. rdmo-plugins-mardmo would be preferred by me.

**Comment by MyPyDavid** [comment]
I have forked it here https://github.com/rdmorganiser/rdmo-plugins-mardmo and added you as a maintainer
